version: "3"

services:
  mysql:
    image: mysql:8.2.0
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: db_java6
      MYSQL_USER: user
      MYSQL_PASSWORD: 123
    ports:
      - "3306:3306"

  redis:
    image: redis:latest
    ports:
      - "6379:6379"
