server:
  port: 8080
  address: 0.0.0.0
  servlet:
    context-path: /api

spring:
  datasource:
    url: jdbc:sqlserver://localhost:1433;databaseName=asm_java6;encrypt=true;trustServerCertificate=true
    username: sa
    password: Qw123456
    driver-class-name: com.microsoft.sqlserver.jdbc.SQLServerDriver
  data:
    redis:
      host: localhost
      port: 6379
