server:
  port: 8080
  address: 0.0.0.0
  servlet:
    context-path: /api

spring:
  datasource:
    url: jdbc:sqlserver://localhost:1433;databaseName=${DB_NAME};encrypt=true;trustServerCertificate=true
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
    driver-class-name: com.microsoft.sqlserver.jdbc.SQLServerDriver
  data:
    redis:
      host: localhost
      port: 6379
  mail:
    host: smtp.gmail.com
    port: 587
    username: thephuongop12@gmail.com
    password: skaq tpnt hbuc dtqh
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
            required: true

security:
  jwt:
    signer-key: "Qn9MjWd1+UXTs0Zmsa3zWGAvgmkIjPo5qPshFUvpNMUbONas1kn5+KY+jp6s4QfO"
    access-token-valid-duration: 10 # minutes
    refresh-token-valid-duration: 30 # minutes

# variables
redis:
  cart-config:
    expiration-time: 30 # minutes
    key-prefix-cart: "cart:"
    key-suffix-order: ":order"
  register-otp-config:
    key-pending-user: "register:pending_user:"
    key-otp: "register:otp:"
    key-duration-resend-otp: "register:duration_resend_otp:"
    expiration-time-pending-user: 30 # minutes
    expiration-time-otp: 3 # minutes
    expiration-time-resend-otp: 1 #minutes
